version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    command: celery -A celery_app.celery worker --loglevel=info
